
services:
  frontend:
    # Build your Next.js app
    build:
      context: .                     # repo root
      dockerfile: Dockerfile.frontend
      target: production
    image: ctf-frontend:latest      # optional tag
    ports:
      - "6030:3000"                  # host:container
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://ctf.av0idd4rk.ru:8080"
    networks:
      - ctf-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6030/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  ctf-net:
    external: true
