networks:
  ctf-net:
    name: ctf-net
  data: {}
services:
  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ctf-net"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.tcp.address=:9000"
    ports:
      - "80:80"
      - "9000:9000"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ctf-net
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctf_deploy
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf -d ctf_deploy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - data

  redis:
    image: redis:latest
    command: ["redis-server", "--save", ""]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - data

  api_gateway:
    build:
      context: .
      dockerfile: crates/api_gateway/Dockerfile
      network: host
    image: ctf-api-gateway
    container_name: ctf-api-gateway
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgres://ctf:ctf_pass@postgres/ctf_deploy"
    ports:
      - "8080:8080"
    networks:
      - data
      - ctf-net
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock


  scheduler:
    build:
      context: .
      dockerfile: crates/scheduler_service/Dockerfile
      network: host
    image: ctf-scheduler
    container_name: ctf-scheduler
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgres://ctf:ctf_pass@postgres/ctf_deploy"
    networks:
      - data
      - ctf-net
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  redis_data:
