services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctf_deploy
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: ["redis-server", "--save", ""]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  api_gateway:
    build:
      context: .
      dockerfile: crates/api_gateway/Dockerfile
      network: host
    image: ctf-api-gateway
    container_name: ctf-api-gateway
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://ctf:ctf_pass@postgres/ctf_deploy"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app


  scheduler:
    build:
      context: .
      dockerfile: crates/scheduler_service/Dockerfile
      network: host
    image: ctf-scheduler
    container_name: ctf-scheduler
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://ctf:ctf_pass@postgres/ctf_deploy"
    volumes:
      - ./:/app

volumes:
  db_data:
  redis_data:
