version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctf_deploy
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    command: ["redis-server", "--save", ""]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
