[ports]
min = 3000
max = 4000
default = 80
default_ttl_secs = 1800

[database]
url = "postgres://ctf:password@localhost:5432/ctf_deploy"

[redis]
url = "redis://localhost:6379/0"

[captcha]
provider = "recaptcha"
site_key = "YOUR_SITE_KEY"
secret_key = "YOUR_SECRET_KEY"
