[containers]
memory_limit   = "512M"
swap_limit     = "512M"
cpu_quota      = 0.5
pids_limit     = 1000

enable_no_new_privileges = true
read_only_rootfs        = true
enable_tmpfs            = true
tmpfs_size              = "64M"

drop_all_capabilities   = true
add_capabilities        = ["CAP_NET_BIND_SERVICE"]


[ports]
min = 3000
max = 4000
default_ttl_secs = 1800
extend_time_secs = 600

[database]
url = "postgres://ctf:password@pgbouncer:6432/ctf_deploy"


[captcha]
provider = "recaptcha" # not fully implemented
site_key   = "YOUR_SITE_KEY"
secret_key = "YOUR_SECRET_KEY"
verify_url = "https://www.google.com/recaptcha/api/siteverify"

[scheduler]
poll_interval_secs = 10

[sessions]
ttl_hours = 24
max_instances = 2


[routing]
variant        = "traefik"         # or "traefik"
domain         = "localhost"    # for port-variant
traefik_domain = "ctf.av0idd4rk.ru"    # for traefik-variant
http_entry     = "web"          # traefik HTTP entrypoint name
tcp_entry      = "tcp"          # traefik TCP entrypoint name

# Global defaults (optional, task entries override)
[tasks._default]
protocol       = "http"         # "http" or "tcp"
container_port = 3000

# Per-task overrides:
[tasks.foo_task]
protocol       = "http"
container_port = 3000

[tasks.bar_pwn]
protocol       = "tcp"
container_port = 31337
