[ports]
min = 3000
max = 4000
default = 80
default_ttl_secs = 1800
extend_time_secs = 600

[database]
url = "postgres://ctf:password@localhost:5432/ctf_deploy"

[redis]
url = "redis://localhost:6379/1"

[captcha]
provider = "recaptcha"
site_key   = "YOUR_SITE_KEY"
secret_key = "YOUR_SECRET_KEY"
verify_url = "https://www.google.com/recaptcha/api/siteverify"

[scheduler]
poll_interval_secs = 10

[sessions]
ttl_hours = 24
max_instances = 5