[package]
name = "port_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["rt", "macros"] }
redis = { version = "0.32.4", features = ["aio", "tokio-comp"] }
thiserror = "2.0.12"
config_manager = { path = "../config_manager" }
